#define init
global.sprite = sprite_add_weapon("iVBORw0KGgoAAAANSUhEUgAAABQAAAAJCAYAAAAywQxIAAAABmJLR0QASAD9AAgiB8BGAAAACXBIWXMAAAsTAAALEwEAmpwYAAAC5ElEQVQoFQHZAib9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAABMVl0AAAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/0xWXQAAAAAAAAAAAAAAAAAAAAAA5uPhAM7HwgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAObj4QA6QUYAAAAAAAAAAAAAAAAAAAAAADpBhAAAAAAAHhwaAOLk5gAeHBoA4uTmAAAAAACUhnwABAAAAABfLyYAAAAAAAAAAAAAAAAAAAAAANMAAADg3NkAAAAAAAAAAAAAAAAAtKqjADI5PgAaHR8A4NzZAAAAAADg3NkAAAAAAAAAAAAAAAAABAAAAAGh0dr/Xy8mAKHR2gAAAAAAAAAAAAAA2gAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAC326ADgw9UAIBYTAODq7QDB5+0AAAAAAAAAAAAAAAAABAAAAAAAAAAA4OrtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKHR2gAAAAAAweftAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk4ZDavFPcBYAAAAASUVORK5CYII=",3,2)

#define weapon_name
return "ASSAULT FLAK CANNON";

#define weapon_sprt
return global.sprite;

#define weapon_type
return 2;

#define weapon_auto
return false;

#define weapon_load
return 32;

#define weapon_cost
return 6;

#define weapon_swap
return sndSwapShotgun;

#define weapon_area
return 11;

#define weapon_text
return "HEAVY IMPACT";

#define weapon_fire

repeat(3)
{
  if instance_exists(self)
  {
    weapon_post(6, -8, 8);
    sound_play(sndFlakCannon);
    with instance_create(x,y,FlakBullet)
    {
      direction = other.gunangle + (random_range(6, -6) * other.accuracy);
      speed = 12;
      image_angle = direction;
      team = other.team;
    }
	}
  wait(4);
}
